# -*- coding: utf-8 -*-
"""challenge2_Palindrome_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hc7Neb4hOYxcKPxN4MyJJQ8IrqlYqlYl
"""

def check_palindrome():
    # Taking input from user
    user_input = input("Enter a string : ")
    user_input=user_input.lower()

    # reversing the string
    reversed_string = user_input[::-1]


    # checking original string is equal to reverse string
    if user_input == reversed_string:
        print(f"The string '{user_input}' is a palindrome.")
    else:
        print(f"The string '{user_input}' is not a palindrome.")

check_palindrome()