# -*- coding: utf-8 -*-
"""challenge1_send_email.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yM2_f_hoPtYLF9PQEUhpa85h201LuiQH
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

def send_email():
    # Your details
    sender_email = "your_email@gmail.com" # Your_email
    sender_password = "your_password" # Your_password
    receiver_email = "hr@ignitershub.com"

    # Email Envelop
    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = receiver_email
    msg['Subject'] = "Challenge 3 Completed"

    # Email Body
    body = """
    Name: Nitin Giri
    Semester: 03
    Branch: Computer Science and Engineering
    Roll Number: 250216018
    """
    msg.attach(MIMEText(body, 'plain'))

    # Image Attachmnt
    filename = "./sample.jpg" # Put here your image name
    try:
        attachment = open(filename, "rb") # opened image in read binary format

        # converting image to email format
        part = MIMEBase('application', 'octet-stream')
        part.set_payload((attachment).read())
        encoders.encode_base64(part)
        part.add_header('Content-Disposition', f"attachment; filename= {filename}")

        msg.attach(part) # adding image to email
    except Exception as e:
        print(f"Image not found: {e}")

    # Process of sending image(SMTP Server)
    try:
        # we are using email sever and port 587
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls() # Securing the connection
        server.login(sender_email, sender_password) # Login
        text = msg.as_string()
        server.sendmail(sender_email, receiver_email, text) # Email sending
        print("Email successfully sent")
        server.quit()
    except Exception as e:
        print(f"Error in sending email {e}")

# Call Function
send_email()
