# -*- coding: utf-8 -*-
"""challenge4_String_Manipulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-8AewXwKNc0reyW1uPRLYDcaGSxnxlcL
"""

def string_operations():
    sentence = input("Enter a sentence: ")

    # 1. Count the number of words
    words_list = sentence.split() # Making List after breaking sentences
    word_count = len(words_list)

    # 2. Reverse the order of words
    reversed_words_list = words_list[::-1] # Reversing the list
    reversed_sentence = " ".join(reversed_words_list)

    # 3. Replace spaces with hyphens
    modified_sentence = sentence.replace(" ", "-")

    # Finding the output
    print(f"Number of words: {word_count}")
    print(f"Reversed sentence: {reversed_sentence}")
    print(f"Modified sentence: {modified_sentence}")

string_operations()