# -*- coding: utf-8 -*-
"""challenge3_Binary_Search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqAjWU-iv416urKIV1qdq-BWssTogKEP
"""

def binary_search():
    # Humari sorted list
    arr = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
    target = int(input("Enter the target element: "))

    low = 0
    high = len(arr) - 1
    found_index = -1 # if not found default value

    # loop for binar search
    while low <= high:
        mid = (low + high) // 2 # Finding the middle index

        if arr[mid] == target:
            found_index = mid # Element found
            break
        elif arr[mid] < target:
            low = mid + 1 # Target is on the right side
        else:
            high = mid - 1 # Target is on the left side

    if found_index != -1:
        print(f"Element {target} is found at index {found_index}.")
    else:
        print(f"Element {target} is not in the array.")

binary_search()